import React, { useState } from 'react';
import { Helmet } from 'react-helmet';
import { Link } from 'react-router-dom';
import { ArrowLeft, Play } from 'lucide-react';

// ─── Video config ────────────────────────────────────────────────────────────
const YOUTUBE_VIDEO_ID = 'l8V3VjkBtPA';
const THUMBNAIL_URL = `https://img.youtube.com/vi/${YOUTUBE_VIDEO_ID}/maxresdefault.jpg`;
const EMBED_URL = `https://www.youtube.com/embed/${YOUTUBE_VIDEO_ID}?rel=0&modestbranding=1&autoplay=1`;
// ─────────────────────────────────────────────────────────────────────────────

const structuredData = {
  '@context': 'https://schema.org',
  '@type': 'VideoObject',
  name: 'DR.OH in the Beginning — Generative AI Multimedia Experience',
  description:
    'A fully AI-generated multimedia experience produced by Jeremy Carter Och over 5 months in 2025–2026. Every image, video clip, sound effect, and music track generated using Adobe Creative Cloud, Google Gemini/Veo, Suno AI, OpenAI, Lisa AI, Microsoft Designer, YouCut, freesound.org, and Claude AI.',
  thumbnailUrl: THUMBNAIL_URL,
  uploadDate: '2026-05-17T00:00:00-05:00',
  duration: 'PT8M10S',
  contentUrl: `https://www.youtube.com/watch?v=${YOUTUBE_VIDEO_ID}`,
  embedUrl: EMBED_URL,
  publisher: {
    '@type': 'Person',
    name: 'Jeremy Carter Och',
    url: 'https://ochai.dev',
  },
};

// ─── Ticket barcode decoration ───────────────────────────────────────────────
const TicketBarcode = () => (
  <div className="flex gap-[2px] items-end h-9 opacity-40" aria-hidden="true">
    {[28,36,20,32,24,36,18,30,36,22,28,16,34,26,36,20,28,36,24,32].map((h, i) => (
      <span
        key={i}
        className="block w-[2px] bg-amber-400"
        style={{ height: `${h}px` }}
      />
    ))}
  </div>
);

// ─── Facade → iframe swap ────────────────────────────────────────────────────
const VideoFacade = () => {
  const [active, setActive] = useState(false);

  if (active) {
    return (
      <div className="relative w-full rounded-xl overflow-hidden shadow-[0_12px_48px_rgba(0,0,0,0.7)]" style={{ aspectRatio: '16/9' }}>
        <iframe
          className="absolute inset-0 w-full h-full"
          src={EMBED_URL}
          title="DR.OH in the Beginning — Generative AI Multimedia Experience"
          frameBorder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowFullScreen
        />
      </div>
    );
  }

  return (
    <button
      onClick={() => setActive(true)}
      className="relative w-full group cursor-pointer rounded-xl overflow-hidden border border-amber-900/30 shadow-[0_12px_48px_rgba(0,0,0,0.6)]"
      style={{ aspectRatio: '16/9' }}
      aria-label="Play DR.OH in the Beginning"
    >
      <img
        src={THUMBNAIL_URL}
        alt="DR.OH in the Beginning — generative AI multimedia showcase thumbnail"
        className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
        loading="lazy"
      />
      <div className="absolute inset-0 bg-slate-950/50 group-hover:bg-slate-950/35 transition-colors duration-300" />
      <div
        className="absolute inset-0 pointer-events-none"
        style={{ background: 'radial-gradient(ellipse at center, rgba(201,168,76,0.09) 0%, transparent 65%)' }}
      />
      <div className="absolute inset-0 flex flex-col items-center justify-center gap-4">
        <div
          className="w-20 h-20 rounded-full flex items-center justify-center transition-transform duration-200 group-hover:scale-110"
          style={{
            background: 'linear-gradient(135deg, #c9a84c, #8a6820)',
            boxShadow: '0 0 40px rgba(201,168,76,0.35), 0 0 0 1px rgba(201,168,76,0.3)',
          }}
        >
          <Play className="w-8 h-8 fill-slate-950 text-slate-950 ml-1" />
        </div>
        <span className="text-xs uppercase tracking-widest" style={{ color: 'rgba(201,168,76,0.55)' }}>
          Click to watch &nbsp;·&nbsp; 8 min
        </span>
      </div>
    </button>
  );
};

// ─── Page ────────────────────────────────────────────────────────────────────
const Showcase = () => (
  <>
    <Helmet>
      <title>Generative AI Showcase | Professional Portfolio | Jeremy C Och · OchAI.dev</title>
      <meta
        name="description"
        content="DR.OH in the Beginning — a fully AI-generated multimedia experience by Jeremy Carter Och. 5 months in production. Every image, video clip, sound effect, and music track generated by AI."
      />
      <link rel="canonical" href="https://ochai.dev/showcase" />
      <meta property="og:type" content="video.other" />
      <meta property="og:url" content="https://ochai.dev/showcase" />
      <meta property="og:title" content="Generative AI Showcase | Jeremy C Och · OchAI.dev" />
      <meta property="og:description" content="A fully AI-generated multimedia experience — 5 months in production using Adobe, Gemini, Suno, OpenAI, and more." />
      <meta property="og:image" content={THUMBNAIL_URL} />
      <meta property="og:video" content={`https://www.youtube.com/watch?v=${YOUTUBE_VIDEO_ID}`} />
      <meta name="twitter:card" content="player" />
      <meta name="twitter:title" content="Generative AI Showcase | Jeremy C Och · OchAI.dev" />
      <meta name="twitter:description" content="A fully AI-generated multimedia experience — 5 months in production." />
      <meta name="twitter:image" content={THUMBNAIL_URL} />
      <meta name="twitter:player" content={EMBED_URL} />
      <script type="application/ld+json">{JSON.stringify(structuredData)}</script>
    </Helmet>

    <div className="min-h-screen bg-slate-950 pt-24 pb-20">
      <div className="container mx-auto px-4 max-w-3xl">

        {/* Back nav */}
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-slate-400 hover:text-amber-400 transition-colors text-sm mb-10 group"
        >
          <ArrowLeft className="w-4 h-4 group-hover:-translate-x-0.5 transition-transform" />
          ochai.dev
        </Link>

        {/* ── Movie ticket header ───────────────────────────────────────────── */}
        <div
          className="rounded-xl mb-8 relative"
          style={{
            background: 'linear-gradient(135deg, #1a1408 0%, #2a1f08 40%, #1a1408 100%)',
            border: '1px solid rgba(201,168,76,0.28)',
            boxShadow: '0 0 0 1px rgba(0,0,0,0.8), 0 20px 60px rgba(0,0,0,0.5), inset 0 1px 0 rgba(201,168,76,0.12)',
          }}
        >
          {/* Sheen */}
          <div
            className="absolute inset-0 rounded-xl pointer-events-none"
            style={{ background: 'linear-gradient(105deg, transparent 0%, rgba(255,240,120,0.04) 35%, rgba(255,240,120,0.07) 50%, rgba(255,240,120,0.04) 65%, transparent 100%)' }}
          />

          {/* Top section */}
          <div className="px-8 pt-8 pb-6 relative" style={{ borderBottom: '1px dashed rgba(201,168,76,0.2)' }}>
            {/* Notch left */}
            <div className="absolute top-1/2 -translate-y-1/2 w-5 h-5 rounded-full"
              style={{ left: '-10px', background: '#020617', border: '1px solid rgba(201,168,76,0.15)' }} />
            {/* Notch right */}
            <div className="absolute top-1/2 -translate-y-1/2 w-5 h-5 rounded-full"
              style={{ right: '-10px', background: '#020617', border: '1px solid rgba(201,168,76,0.15)' }} />

            <p className="text-xs uppercase tracking-[0.22em] mb-3" style={{ color: 'rgba(201,168,76,0.5)' }}>
              Now Screening &nbsp;·&nbsp; ochai.dev presents
            </p>

            <h1
              className="text-3xl md:text-4xl font-bold leading-tight mb-2"
              style={{
                fontFamily: 'Georgia, "Times New Roman", serif',
                background: 'linear-gradient(135deg, #f0d060 0%, #c9a84c 25%, #ffe680 45%, #b8922e 65%, #e8c84a 80%, #c9a84c 100%)',
                WebkitBackgroundClip: 'text',
                WebkitTextFillColor: 'transparent',
                backgroundClip: 'text',
                filter: 'drop-shadow(0 1px 8px rgba(201,168,76,0.22))',
              }}
            >
              DR.OH in the Beginning
            </h1>

            <p className="text-sm tracking-wide" style={{ color: 'rgba(255,255,255,0.3)' }}>
              A fully AI-generated multimedia experience &nbsp;·&nbsp; 8 min
            </p>
          </div>

          {/* Stub */}
          <div className="px-8 py-5 flex flex-wrap items-center justify-between gap-4">
            {[
              { label: 'Presented by', value: 'Jeremy Carter Och' },
              { label: 'Production', value: '5 months · 2025–2026' },
              { label: 'Format', value: 'AI · Multi-Media' },
            ].map(({ label, value }) => (
              <div key={label} className="flex flex-col gap-0.5">
                <span className="text-[9px] uppercase tracking-[0.18em]" style={{ color: 'rgba(201,168,76,0.45)' }}>{label}</span>
                <span className="text-sm tracking-wide" style={{ color: 'rgba(255,255,255,0.6)' }}>{value}</span>
              </div>
            ))}
            <TicketBarcode />
          </div>
        </div>

        {/* ── Video ─────────────────────────────────────────────────────────── */}
        <VideoFacade />

        {/* Lighthouse badge */}
        <div className="flex justify-center mt-5 mb-14">
          <span
            className="inline-flex items-center gap-2 text-xs tracking-wide px-4 py-1.5 rounded-full"
            style={{ background: 'rgba(201,168,76,0.06)', border: '0.5px solid rgba(201,168,76,0.18)', color: 'rgba(201,168,76,0.5)' }}
          >
            <span className="w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ background: '#c9a84c', opacity: 0.65 }} />
            Lighthouse 100 · zero embed weight on load
          </span>
        </div>

        {/* ── Production notes ──────────────────────────────────────────────── */}
        <div
          className="rounded-xl p-8 mb-6"
          style={{ background: 'rgba(15,15,25,0.7)', border: '0.5px solid rgba(255,255,255,0.06)' }}
        >
          <h2 className="text-base font-semibold text-white mb-5 tracking-wide uppercase" style={{ letterSpacing: '0.1em' }}>
            Production Notes
          </h2>
          <div className="space-y-4 text-slate-400 text-sm leading-relaxed">
            <p>
              What started as a New Year's Day post grew — over five months — into something else
              entirely. Every image, video clip, sound effect, and music track in this production
              was generated by AI. No stock footage. No licensed audio. No pre-existing assets.
            </p>
            <p>
              The technical mountain: generative video models cap at 8-second scenes. Building
              a coherent 8-minute experience from clips that short — while stripping and replacing
              all generated audio from the side — is a different kind of production problem. More
              virtual tape hit the floor than made the cut.
            </p>
            <p>
              The tools that made it possible, in no particular order of gratitude:
            </p>
          </div>

          {/* Credits grid */}
          <div className="mt-6 grid grid-cols-2 md:grid-cols-3 gap-3">
            {[
              'Adobe Creative Cloud',
              'Google Gemini / Veo',
              'Suno AI',
              'OpenAI',
              'Lisa AI',
              'Microsoft Designer',
              'YouCut',
              'freesound.org',
              'Claude AI',
            ].map((tool) => (
              <div
                key={tool}
                className="rounded-lg px-3 py-2 text-xs text-center tracking-wide"
                style={{ background: 'rgba(201,168,76,0.05)', border: '0.5px solid rgba(201,168,76,0.15)', color: 'rgba(201,168,76,0.65)' }}
              >
                {tool}
              </div>
            ))}
          </div>

          <p className="text-slate-500 text-xs mt-6 leading-relaxed">
            — Jeremy Carter Och &nbsp;·&nbsp; Full-Stack AI Implementation Digital Operator &nbsp;·&nbsp;{' '}
            <a href="mailto:jeremy@ochai.dev" className="hover:text-amber-400 transition-colors">jeremy@ochai.dev</a>
          </p>
        </div>

        {/* ── CTA ───────────────────────────────────────────────────────────── */}
        <div className="text-center pt-4">
          <Link
            to="/#contact"
            className="inline-flex items-center gap-2 px-8 py-3 rounded-full text-sm font-medium transition-all duration-200 hover:scale-105"
            style={{
              background: 'linear-gradient(135deg, #c9a84c, #8a6820)',
              color: '#020617',
              boxShadow: '0 0 28px rgba(201,168,76,0.25)',
            }}
          >
            Start the Conversation
          </Link>
        </div>

      </div>
    </div>
  </>
);

export default Showcase;
